spring:
  application:
    name: ikon-message-consumer

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 0





eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

message:
  topic:
    private:
      name: my-first-chat-topic