spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: userservice

  data:
    redis:
      host: localhost
      port: 6379
      password: javed308


server:
  port: 9091


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka